source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'slim'
gem 'sass'
gem 'uglifier'
gem 'thin'
gem 'dm-core'
gem 'dm-pager'
gem 'dm-types'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-sqlite-adapter'

